# 공통 설정

spring:
  config:
    type: aws-parameterstore:/config/hid-prd/

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

      # Secret Key 은닉 필요
      #application:
      #security:
      #jwt:
    #expiration:

---
# Dev 환경 설정 - 환경변수 설정
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/test # 도커 실행 시 host.docker.internal
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    aws:
      credentials:
        access-key: AKIA356SJRQL66537PUS
        secret-key: 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
      region:
        static: ap-northeast-2
      #cloudfront-domain: ${CLOUDFRONT_DOMAIN}
---
